# Generated by Django 3.2.7 on 2025-01-10 03:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Reported phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, help_text='Optional description of spam activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(help_text='User who reported the spam', on_delete=django.db.models.deletion.CASCADE, related_name='spam_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'spam report',
                'verbose_name_plural': 'spam reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spamreport',
            index=models.Index(fields=['phone_number'], name='spam_spamre_phone_n_0fbf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='spamreport',
            index=models.Index(fields=['created_at'], name='spam_spamre_created_a0e51c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spamreport',
            unique_together={('reporter', 'phone_number')},
        ),
    ]
